title: Royally-Handmade
description: An organized chaos of collective thoughts. 
author:
  name: Courtney Campbell
url: https://royally-handmade.github.io
github_username: royally-handmade
github_url: https://royally-handmade.github.io/
repository: royally-handmade/royally-handmade.github.io

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
gist:
noscript: false